[tool.black]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.egg-info
    | \.git
    | \.vscode
    | \.tox
    | \.mypy_cache
    | \.venv
    | __pycache__
    | venv
    | build
    | dist
    | \.history
    | example/LLM/belle-bloom/BELLE
    | starwhale/proto_gen
  )/
)
'''

[tool.mypy]
exclude = [
    "venv/",
    "build/",
    "dist/",
    "__pycache__/",
    "tests/",
    "dummy/setup.py",
    "example/LLM/belle-bloom/BELLE/",
    "starwhale/proto_gen/",
]
show_column_numbers = true
ignore_missing_imports = true
follow_imports = "silent"
check_untyped_defs = true
disallow_untyped_calls = true
warn_unused_configs = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
strict_optional = true
plugins = [ "trio_typing.plugin" ]

[tool.isort]
profile = "black"
multi_line_output = 3
length_sort = true
order_by_type = true
force_alphabetical_sort_within_sections = true
extend_skip_glob="../example/LLM/belle-bloom/BELLE/*,starwhale/proto_gen/*"
