[tool.black]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.egg-info
    | \.git
    | \.vscode
    | \.tox
    | \.mypy_cache
    | \.venv
    | __pycache__
    | venv
    | build
    | dist
  )/
)
'''

[tool.mypy]
exclude = [
    "venv",
    "build",
    "dist",
    "__pycache__",
]
show_column_numbers = true
ignore_missing_imports = true
follow_imports = "silent"
disallow_untyped_defs = false
check_untyped_defs = true
# Strict mode
disallow_untyped_calls = false
no_implicit_optional = false
disallow_incomplete_defs = false
disallow_subclassing_any = false
strict_optional = false
warn_unused_ignores = false
warn_unused_configs = false
warn_redundant_casts = false
warn_return_any = false