server:
  port: ${SW_AGENT_PORT:8088}
sw:
  agent:
    version: ${SW_AGENT_VERSION:0.1.0}
    basePath: ${SW_BASE_PATH:/opt/starwhale}
    hostIP: ${SW_HOST_IP:127.0.0.1}
    task:
      retryRunMaxNum: 10
      retryRestartMaxNum: 10
      pypiIndexUrl: ${SW_PYPI_INDEX_URL:http://10.131.0.1:3141/root/pypi-douban/+simple/}
      pypiExtraIndexUrl: ${SW_PYPI_EXTRA_INDEX_URL:https://pypi.tuna.tsinghua.edu.cn/simple/}
      pypiTrustedHost: ${SW_PYPI_TRUSTED_HOST:10.131.0.1 pypi.tuna.tsinghua.edu.cn}
  controller:
    name: swController
    url: ${SW_CONTROLLER_URL:http://10.131.0.1:8082/}
  container:
    host: ${DOCKER_HOST:tcp://127.0.0.1:2376}
  storage:
    type: s3
    path-prefix: ${SW_STORAGE_PREFIX:StarWhale}
    s3-config:
      bucket: ${SW_STORAGE_BUCKET:starwhale}
      accessKey: ${SW_STORAGE_ACCESSKEY:accessKey}
      secretKey: ${SW_STORAGE_SECRETKEY:secretKey}
      region: ${SW_STORAGE_REGION:region}
      endpoint: ${SW_STORAGE_ENDPOINT:http://10.131.0.1:9000}